### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Teddy95** [fabianfiorotto/xatom-debug-php#1]
Hey!

I've installed xdebug and testet it successfully with php-debug extension for atom but I didn't get it to work with xatom-debug-php, can you help me please?

**Comment by fabianfiorotto** [comment]
Do you get the "Listening" message when you click on the play button? Keep in mind that you can only have a process listening on 9000 at once.

![imagen](https://user-images.githubusercontent.com/898842/63771542-bf8b8500-c8ad-11e9-8c8b-4dea3045cbc0.png)

**Comment by Teddy95** [comment]
Yes the debugger is listening on port 9000

**Comment by fabianfiorotto** [comment]
Also, make sure that the breakpoints you are setting are from xatom-debug. Those are shaped as pentagons. Did you disable `php-debug` before test?

**Comment by Teddy95** [comment]
Yes & php-debug is already uninstalled :)

<img width="1292" alt="Bildschirmfoto 2019-08-27 um 18 39 56" src="https://user-images.githubusercontent.com/3901133/63790752-436b5e80-c8fa-11e9-9db3-cf49969acbd3.png">

**Comment by Teddy95** [comment]
My xdebug.ini configurations are the following:

```
[xdebug]
zend_extension="xdebug.so"
xdebug.default_enalbe=1
xdebug.remote_enable=1
xdebug.remote_host=192.168.2.104  # Remote IP Host
xdebug.remote_connect_back=1
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_autostart=true
xdebug.idekey=xdebug-atom
```

**Comment by fabianfiorotto** [comment]
I was blocking connections from other hosts. Now should be fixed. Please, try again.
