### ISSUE TITLE
Support path maps to map container or virtualized paths

### ISSUE THREAD

**Issue by ghost** [fabianfiorotto/xatom-debug-php#2]
Hello

I can get this plugin to work and the "Listening" symbol to appear correctly. However, my breakpoints are never triggered (and nothing is logged in the console). I assume that this is due to missing support for path maps, as my environment runs on a Docker container that uses different paths than Atom needs to open on the host.

Would it be possible to add path map support? This could be something simple like `/var/www/app/someproject` is actually `/home/user/ProjectsOnHost/project/`. Since users usually have different projects, a list of these would probably be ideal.

php-debug also supports this, if you'd like to peek at other implementations :-).

Thanks for your work on making the PHP package ecosystem in Atom better, especially now that it seems the other PHP debugging plugins are unmaintained!

**Comment by fabianfiorotto** [comment]
I added an option to set a map path. The files are mapped from the project folder in atom to the given folder on the server.
XAtom Debug uses the workspace storage for the settings so you can set different values for different projects. 

What is not clear for me is what should happen when the break gets to a file outside the mapping. 
I could request the code to xdebug and show it in a temp file but implement such behavior would take a lot of work.

About the maintenance of php-debug. xatom-debug is also unmaintained sadly.
I could code my own GUI for this package but that would require a lot of work and would make fragmentation in atom even worse.
If this package success, we could think in create a new GUI with the same API.

**Comment by ghost** [comment]
Thanks, that fixes the problem for me, and pretty neatly at that since it's saved per workspace :+1:.

IIRC, the php-debug package showed a dialog that a breakpoint was triggered on an unknown or nonexistent path and asked what it should be mapped to (i.e. it asked you to configure a path map for it). This would require support for multiple path maps per project, though.

Also, if the path map isn't set up properly or the file still isn't found, I think php-debug just ignored it. You could also just log a warning somewhere in a log that is visible to the user (or, if there is none, the developer tools log using `console.log`; it's still better than nothing).

In any case, I'm glad that there is now at least one debugging plugin working again :smile: .

There used to be the debugging UI in atom-ide-ui, but I think it used its own protocol that you would need to convert to and from the Xdebug protocol. Also, it is _also_ unmaintained since Facebook abandoned it. Still, the [atom-ide-community project](https://atom-ide-community.github.io/) is steadily picking it up again, so perhaps they will also include a new debugger. See also [here](https://github.com/atom-ide-community/atom-ide-community.github.io/issues/3).

**Comment by fabianfiorotto** [comment]
I don't like atom-ide. I just tried it once and then deleted it. It made atom super slow and it is full of bloatware. I'm not going to go that way.
