### ISSUE TITLE
I cant understand what is the "relative project path files location in the server"

### ISSUE THREAD

**Issue by fapchat2** [fabianfiorotto/xatom-debug-php#3]
![Снимок экрана от 2019-10-30 19-43-19](https://user-images.githubusercontent.com/51196762/67883219-bc826e80-fb54-11e9-822a-bc35a249d99a.png)

Where is it on the ubuntu 18.04? php 7.3.10

**Comment by fabianfiorotto** [comment]
Is apache running in the same machine that atom? or is it in a remote server, a VM or Docker container? 
If apache is running on the same machine then you don't need to put anything there. Just left it blank.
